name: Test

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: |
        git config --global user.name 'AmbNum Bot'
        git config --global user.email 'ambnum.bot@disinfo.quaidorsay.fr'
    - run: npm run validate:schema
    - run: npm test
